# -*- coding: utf-8 -*-
"""Dataset Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gfW2L-9sF3VIsSKi9IEmIiNvB7p86zjq
"""

import pandas as pd
import numpy as np

train_X = pd.read_csv('music_data/train_X.csv')
test_X = pd.read_csv('music_data/test_X.csv')
val_X = pd.read_csv('music_data/valid_X.csv')
train_y = pd.read_csv('music_data/train_Y.csv')
test_y = pd.read_csv('music_data/test_Y.csv')
val_y = pd.read_csv('music_data/valid_Y.csv')

def get_basic_info(name, x, y):
    print('======', name, '======')
    print('X Dimension:', x.shape)
    print('Y Dimension:', y.shape)
    print('Y Ratio:', sum(y['target'])/y.shape[0])

get_basic_info('Train Data', train_X, train_y)
get_basic_info('Test Data', test_X, test_y)
get_basic_info('Validation Data', val_X, val_y)

