# -*- coding: utf-8 -*-
"""Create_Features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzMsHC6ZBNgQ6_7L4udh2qlrHowMEC84
"""

from itertools import combinations

import pandas as pd
import numpy as np
import scipy.sparse as sp
from scipy.sparse import coo_matrix
from lightfm import LightFM
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

date_cols = ['expiration_date', 'registration_init_time']

train_data = pd.read_csv('music_data_raw/train_data_updated.csv', parse_dates=date_cols)
test_data = pd.read_csv('music_data_raw/test_data_updated.csv', parse_dates=date_cols)
all_data = pd.concat([train_data, test_data])
all_data[:3]

print(all_data.shape)
print(np.count_nonzero(all_data['target'])/all_data.shape[0])

test_data.info()

catCols = ['msno', 'song_id', 'source_screen_name', 'source_system_tab', 'source_type', 'genre_ids', 'artist_name', 
           'composer', 'lyricist', 'language', 'city', 'gender', 'registered_via']
numCols = ['bd', 'song_length']

vis1 = sns.distplot(test_data["bd"], bins = 80)
plt.xlim(0, 100)

